version: 2
updates:
  - package-ecosystem: "docker"
    open-pull-requests-limit: 10
    directory: "/docker/postgres-dvd"
    schedule:
      interval: "weekly"
      time: "05:00"
  - package-ecosystem: "docker"
    open-pull-requests-limit: 10
    directory: "/docker/maysql-sakila"
    schedule:
      interval: "weekly"
      time: "05:00"
  - package-ecosystem: "docker"
    open-pull-requests-limit: 10
    directory: "/docker/orientdb3"
    schedule:
      interval: "weekly"
      time: "05:00"
